/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.kasir;
import java.util.logging.*;
import java.sql.*;
import javax.swing.JOptionPane;
import Model.DataPenggunaModel;
import Manajer.DataPenggunaManajer;
/**
 *
 * @author Raehan Reza M
 */
public class Register extends javax.swing.JFrame {
    int akunID = 0;
    DataPenggunaModel datapenggunaGlobal;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }
    
    public void showMessage(String message, int type){
        if(type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean validateInput() throws SQLException{
        boolean isCompleted = false;
        DataPenggunaModel dp = new DataPenggunaModel();
        //Namapengguna
        if(baNama.getText().isEmpty()){
            isCompleted = false;
            baNama.requestFocus();
        }else{
            dp.setNama_Pengguna(baNama.getText());
            isCompleted = true;
        }
        //username
        if(caUsername.getText().isEmpty()){
            isCompleted = false;
            caUsername.requestFocus();
        }else{
            dp.setUsername(caUsername.getText());
            isCompleted = true;
        }
        //password
        if(pfPass.getText().isEmpty()){
            isCompleted = false;
            pfPass.requestFocus();
        }else{
            dp.setPassword_pengguna(pfPass.getText());
            isCompleted = true;
        }
        
        datapenggunaGlobal = dp;
        if(!isCompleted){
            showMessage("Data harus dilengkapi!", 2);
            return false;
        }else{
            showMessage("Akun sudah ditambahkan silahkan login", 1);
            dispose();
            return true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        abNama = new javax.swing.JLabel();
        acUsername = new javax.swing.JLabel();
        aaPassword = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        pfPass = new javax.swing.JPasswordField();
        baNama = new javax.swing.JTextField();
        caUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adobe Arabic", 3, 24)); // NOI18N
        jLabel1.setText("APLIKASI THRIFTING JACKET");

        abNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        abNama.setText("Nama Pengguna ");

        acUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acUsername.setText("Username");

        aaPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aaPassword.setText("Password");

        btRegister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRegister.setText("REGISTER");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        baNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baNamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aaPassword)
                    .addComponent(abNama)
                    .addComponent(acUsername))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRegister)
                    .addComponent(pfPass, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(baNama)
                    .addComponent(caUsername))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abNama)
                    .addComponent(baNama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(acUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(caUsername)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aaPassword))
                .addGap(40, 40, 40)
                .addComponent(btRegister)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baNamaActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        // TODO add your handling code here:
        try{
            if(validateInput()){
                DataPenggunaManajer.tambahAkun(datapenggunaGlobal);
            }
        }catch(SQLException ex){
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaPassword;
    private javax.swing.JLabel abNama;
    private javax.swing.JLabel acUsername;
    private javax.swing.JTextField baNama;
    private javax.swing.JButton btRegister;
    private javax.swing.JTextField caUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pfPass;
    // End of variables declaration//GEN-END:variables
}
