/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataTransaksi;


import Model.DataBarangModelStatic;
import DataMenu.DataMenu;
import Manajer.DataTransaksiManajer;
import Model.DataTransaksiModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Raehan Reza M
 */
public class DataTransaksi extends javax.swing.JFrame {
    DataTransaksiModel transaksiGlobal;
    //DataBarangModel db = new DataBarangModel();
    int kodeBarang = DataBarangModelStatic.getIdDataBarang();
    String namaBarang = DataBarangModelStatic.getNama_Barang();
    int hargaBarang = DataBarangModelStatic.getHarga_Barang();
    int hargaJualBarang = DataBarangModelStatic.getHarga_jual_barang();
    int stockBarang = DataBarangModelStatic.getStock_Barang();
    //Akun ak = new Akun();
    /**
     * Creates new form MainWindow
     */
     public DataTransaksi() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataPaket();
    }
    
    public void showMessage(String message, int type){
        if(type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void clear(){
        akKode.setText("");
        akHarga.setText("");
        amPembelian.setText("");
        anTotalPembayaran.setText("");
    }
    
    public void loadDataPaket(){
        akKode.setText(String.valueOf(kodeBarang));
        akNamaPaket.setText(namaBarang);
        akHarga.setText(String.valueOf(hargaBarang));
    }
    
    private boolean validasiInput() throws SQLException{
        boolean isCompleted = false;
        DataTransaksiModel dtm = new DataTransaksiModel();
        //Text Field
        if (akKode.getText().isEmpty()){
            isCompleted = false;
            akKode.requestFocus();
        }else{
            dtm.setIdDataBarang(Integer.parseInt(akKode.getText()));
            isCompleted = true;
        }
        
        if (anPembayaran.getText().isEmpty()){
            isCompleted = false;
            anPembayaran.requestFocus();
        }else{
            dtm.setPembayaran(Integer.parseInt(anPembayaran.getText()));
            isCompleted = true;
        }
        
        if (anKembalian.getText().isEmpty()){
            isCompleted = false;
            anKembalian.requestFocus();
        }else{
            dtm.setKembalian(Integer.parseInt(anKembalian.getText()));
            isCompleted = true;
        }
        
        
        transaksiGlobal = dtm;
        if (!isCompleted) {
            showMessage("Silahkan isi dulu!", 2);
            return false;
        } else {
            return true;
        }
    }
    
    private void getTotal(){
        try {
            int harga = Integer.parseInt(akHarga.getText());
            int jumlah = Integer.parseInt(amPembelian.getText());
            int total = (harga * jumlah);
            anTotalPembayaran.setText(String.valueOf(total));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    private void kembalian(){
	try {
            int bayar = Integer.parseInt(anPembayaran.getText());
            int total = Integer.parseInt(anTotalPembayaran.getText());
            int kembali = (bayar - total);
            anKembalian.setText(String.valueOf(kembali));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        asKode = new javax.swing.JLabel();
        btBeli = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        akKode = new javax.swing.JTextField();
        akHarga = new javax.swing.JTextField();
        adharga = new javax.swing.JLabel();
        amPembelian = new javax.swing.JTextField();
        aePembelian = new javax.swing.JLabel();
        anTotalPembayaran = new javax.swing.JTextField();
        atTotalPembayaran = new javax.swing.JLabel();
        btPilihPaket = new javax.swing.JButton();
        akNamaPaket = new javax.swing.JTextField();
        adNamaPaket = new javax.swing.JLabel();
        anPembayaran = new javax.swing.JTextField();
        atPembayaran = new javax.swing.JLabel();
        anKembalian = new javax.swing.JTextField();
        atKembalian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adobe Arabic", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI THRIFTING JACKET");
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(557, 333));

        asKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asKode.setText("Kode Barang :");

        btBeli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBeli.setText("Beli");
        btBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBeliActionPerformed(evt);
            }
        });

        btRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        btBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btBack.setText("< Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Adobe Arabic", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA TRANSAKSI");
        jLabel4.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(557, 333));

        akKode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        akKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akKodeActionPerformed(evt);
            }
        });

        akHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        akHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akHargaActionPerformed(evt);
            }
        });

        adharga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adharga.setText("Harga Barang :");

        amPembelian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amPembelianActionPerformed(evt);
            }
        });

        aePembelian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aePembelian.setText("Pembelian :");

        anTotalPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        anTotalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anTotalPembayaranActionPerformed(evt);
            }
        });

        atTotalPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atTotalPembayaran.setText("Total Pembayaran :");

        btPilihPaket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPilihPaket.setText("Pilih Paket");
        btPilihPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPilihPaketActionPerformed(evt);
            }
        });

        akNamaPaket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        akNamaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akNamaPaketActionPerformed(evt);
            }
        });

        adNamaPaket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adNamaPaket.setText("Nama Paket:");

        anPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        anPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anPembayaranActionPerformed(evt);
            }
        });

        atPembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atPembayaran.setText("Pembayaran:");

        anKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        anKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anKembalianActionPerformed(evt);
            }
        });

        atKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atKembalian.setText("Kembalian:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btPilihPaket)
                                .addGap(18, 18, 18)
                                .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(asKode)
                                        .addGap(51, 51, 51)
                                        .addComponent(akKode, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(atPembayaran)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(anPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(adharga)
                                            .addComponent(aePembelian)
                                            .addComponent(adNamaPaket))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(amPembelian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(akHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(akNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(atTotalPembayaran)
                                        .addGap(18, 18, 18)
                                        .addComponent(anTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(atKembalian)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(anKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(87, 87, 87)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asKode)
                    .addComponent(akKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adNamaPaket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adharga)
                    .addComponent(akHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aePembelian)
                    .addComponent(amPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atTotalPembayaran)
                    .addComponent(anTotalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atPembayaran)
                    .addComponent(anPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atKembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btBack)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBeli)
                            .addComponent(btRefresh)
                            .addComponent(btPilihPaket))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new DataMenu().setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBeliActionPerformed
        // TODO add your handling code here:
        try {
            if (validasiInput()) {
                DataTransaksiManajer.insertPembayaran(transaksiGlobal);
                showMessage("Terimakasih", 1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBeliActionPerformed

    private void akHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akHargaActionPerformed

    private void amPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amPembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amPembelianActionPerformed

    private void anTotalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anTotalPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anTotalPembayaranActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        // TODO add your handling code here:
        loadDataPaket();
        getTotal();
        kembalian();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void akKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akKodeActionPerformed

    private void btPilihPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPilihPaketActionPerformed
        // TODO add your handling code here:
        new ProdukWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btPilihPaketActionPerformed

    private void akNamaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akNamaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akNamaPaketActionPerformed

    private void anPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anPembayaranActionPerformed

    private void anKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anKembalianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adNamaPaket;
    private javax.swing.JLabel adharga;
    private javax.swing.JLabel aePembelian;
    private javax.swing.JTextField akHarga;
    private javax.swing.JTextField akKode;
    private javax.swing.JTextField akNamaPaket;
    private javax.swing.JTextField amPembelian;
    private javax.swing.JTextField anKembalian;
    private javax.swing.JTextField anPembayaran;
    private javax.swing.JTextField anTotalPembayaran;
    private javax.swing.JLabel asKode;
    private javax.swing.JLabel atKembalian;
    private javax.swing.JLabel atPembayaran;
    private javax.swing.JLabel atTotalPembayaran;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBeli;
    private javax.swing.JButton btPilihPaket;
    private javax.swing.JButton btRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
