/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataTransaksi;

import javax.swing.JOptionPane;
import KoneksiHelper.Koneksi;
import Model.DataBarangModelStatic;
import java.util.logging.*;
import java.sql.*;
/**
 *
 * @author Raehan Reza M
 */
public class ProdukWindow extends javax.swing.JFrame {

    /**
     * Creates new form ProdukWindow
     */
    public ProdukWindow() {
        initComponents();
    }
    
    public void showMessage(String message, int type){
        if (type == 1){
            JOptionPane.showMessageDialog(this, message, "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        asPaket1 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        asPaket2 = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        asPaket3 = new javax.swing.JRadioButton();
        btDone = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("PILIH PAKET BARANG");

        asPaket1.setText("Paket1");
        asPaket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asPaket1ActionPerformed(evt);
            }
        });

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Bebas", 0, 15)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("- Rp 150.000\n\n-Jacket Outdor 2\n\n- Merk Random");
        jScrollPane5.setViewportView(jTextArea5);

        asPaket2.setText("Paket2");
        asPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asPaket2ActionPerformed(evt);
            }
        });

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Bebas", 0, 15)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("- Rp 210.000\n\n-Jacket Outdor 3\n\n- Merk Random ");
        jScrollPane6.setViewportView(jTextArea6);

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Bebas", 0, 15)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("- Rp 250.000\n\n-Jacket Outdor 4\n\n- Merk Random ");
        jScrollPane7.setViewportView(jTextArea7);

        asPaket3.setText("Paket2");
        asPaket3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asPaket3ActionPerformed(evt);
            }
        });

        btDone.setText("Done");
        btDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoneActionPerformed(evt);
            }
        });

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btDone, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btCancel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(asPaket1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(asPaket2))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(asPaket3))
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asPaket1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asPaket2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asPaket3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDone)
                    .addComponent(btCancel))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asPaket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asPaket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asPaket1ActionPerformed

    private void asPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asPaket2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asPaket2ActionPerformed

    private void asPaket3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asPaket3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asPaket3ActionPerformed

    private void btDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoneActionPerformed
        // TODO add your handling code here:
        //DataBarangModel dbm = new DataBarangModel();
        if(asPaket1.isSelected()){
            try{
                Connection conn = Koneksi.getConnection();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM barang WHERE idDataBarang = 1";
                ResultSet rs = st.executeQuery(sql);

                if(rs.next()){
                    DataBarangModelStatic.setIdDataBarang(rs.getInt("idDataBarang"));
                    DataBarangModelStatic.setNama_Barang(rs.getString("Nama_Barang"));
                    DataBarangModelStatic.setHarga_Barang(Integer.parseInt(rs.getString("Harga_Barang")));
                    DataBarangModelStatic.setStock_Barang(Integer.parseInt(rs.getString("Stock_Barang")));
                    DataBarangModelStatic.setHarga_jual_barang(Integer.parseInt(rs.getString("Harga_jual_barang")));
                    JOptionPane.showMessageDialog(null, "Paket dipilih");
                    dispose();
                    new DataTransaksi().setVisible(true);
                }
            }catch(SQLException e){
                Logger.getLogger(ProdukWindow.class.getName()).log(Level.SEVERE, null, e);
            }
        }else if(asPaket2.isSelected()){
            try{
                Connection conn = ConnectionHelper.getConnection();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM paket_internet WHERE id_paket = 2";
                ResultSet rs = st.executeQuery(sql);

                if(rs.next()){
                    DataBarangModelStatic.setIdDataBarang(rs.getInt("idDataBarang"));
                    DataBarangModelStatic.setNama_Barang(rs.getString("Nama_Barang"));
                    DataBarangModelStatic.setHarga_Barang(Integer.parseInt(rs.getString("Harga_Barang")));
                    DataBarangModelStatic.setStock_Barang(Integer.parseInt(rs.getString("Stock_Barang")));
                    DataBarangModelStatic.setHarga_jual_barang(Integer.parseInt(rs.getString("Harga_jual_barang")));
                    JOptionPane.showMessageDialog(null, "Paket dipilih");
                    dispose();
                    new DataTransaksi().setVisible(true);
                }
            }catch(SQLException e){
                Logger.getLogger(ProdukWindow.class.getName()).log(Level.SEVERE, null, e);
            }
        }else if(asPaket3.isSelected()){
            try{
                Connection conn = ConnectionHelper.getConnection();
                Statement st = conn.createStatement();
                String sql = "SELECT * FROM paket_internet WHERE id_paket = 3";
                ResultSet rs = st.executeQuery(sql);

                if(rs.next()){
                    DataBarangModelStatic.setIdDataBarang(rs.getInt("idDataBarang"));
                    DataBarangModelStatic.setNama_Barang(rs.getString("Nama_Barang"));
                    DataBarangModelStatic.setHarga_Barang(Integer.parseInt(rs.getString("Harga_Barang")));
                    DataBarangModelStatic.setStock_Barang(Integer.parseInt(rs.getString("Stock_Barang")));
                    DataBarangModelStatic.setHarga_jual_barang(Integer.parseInt(rs.getString("Harga_jual_barang")));
                    JOptionPane.showMessageDialog(null, "Paket dipilih");
                    dispose();
                    new DataTransaksi().setVisible(true);
                }
            }catch(SQLException e){
                Logger.getLogger(ProdukWindow.class.getName()).log(Level.SEVERE, null, e);
            }
        }

        /**
        try{
            Connection conn = ConnectionHelper.getConnection();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM paket_internet WHERE id_paket = ?";
            ResultSet rs = st.executeQuery(sql);

            if(rs.next()){
                if(rbSicepat.isSelected()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rbSicepat.getText());
                }else if(rbSikilat.isSelected()){
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rbSikilat.getText());
                }else{
                    PaketInternet.setId_paket(rs.getInt("id_paket"));
                    PaketInternet.setNama_paket(rbSiflash.getText());
                }
            }
        }catch(SQLException e){
            Logger.getLogger(PaketWindow.class.getName()).log(Level.SEVERE, null, e);
        }
        **/
    }//GEN-LAST:event_btDoneActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        new DataTransaksi().setVisible(true);
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdukWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdukWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton asPaket1;
    private javax.swing.JRadioButton asPaket2;
    private javax.swing.JRadioButton asPaket3;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    // End of variables declaration//GEN-END:variables
}
